# =============================================================================
#   BOOK RECOMMENDER SYSTEM  —  TKINTER DESKTOP APP  (app.py)
#   Run this file in VS Code after generating the .pkl files from Jupyter
# =============================================================================
#
#  HOW THIS APP WORKS
#  ------------------
#  1. Loads 4 pickle files saved from the Jupyter notebook:
#       popular.pkl            →  Top-50 popular books  (DataFrame)
#       pt.pkl                 →  User-Book pivot table  (706 × 810)
#       books.pkl              →  Full books DataFrame  (title, author, image URL)
#       similarity_scores.pkl  →  Cosine similarity matrix  (706 × 706)
#
#  2. Opens a full-screen dark-themed Tkinter window with TWO tabs:
#       Tab 1 — Top 50 Popular Books   : grid of book cards with cover + rating
#       Tab 2 — Recommend Books        : search box → 4 similar books returned
#
#  HOW TO RUN
#  ----------
#  Step 1:  Run the Jupyter notebook fully (all cells) to create the 4 .pkl files
#  Step 2:  Place app.py in the SAME FOLDER as the 4 .pkl files
#  Step 3:  pip install pillow requests numpy pandas
#  Step 4:  python app.py
#
#  FOLDER STRUCTURE
#  ----------------
#  project/
#  ├── books.csv
#  ├── users.csv
#  ├── ratings.csv
#  ├── book-recommender-system.ipynb   ← run this first
#  ├── popular.pkl                     ← generated by notebook
#  ├── pt.pkl                          ← generated by notebook
#  ├── books.pkl                       ← generated by notebook
#  ├── similarity_scores.pkl           ← generated by notebook
#  └── app.py                          ← THIS FILE  (run with: python app.py)
# =============================================================================


# ─────────────────────────────────────────────────────────────────────────────
#  IMPORTS
# ─────────────────────────────────────────────────────────────────────────────

# Standard library — no pip install needed
import os           # os.path.join, os.getcwd, os.path.exists
import pickle       # deserialise the .pkl model files
import threading    # download images in background so the UI never freezes
from io import BytesIO  # wrap raw image bytes as a file-like object for PIL

# Tkinter — Python's built-in GUI toolkit (no pip install needed)
import tkinter as tk             # core widgets: Tk, Frame, Label, Button, Entry
import tkinter.ttk as ttk        # themed widgets: Notebook, Scrollbar
from tkinter import messagebox   # pop-up error / info dialogs

# Third-party — install with:  pip install numpy pandas pillow requests
import numpy as np    # np.where used to find a book's row index in the pivot table
import pandas as pd   # DataFrame operations on the loaded model files

# Pillow — image loading, resizing, conversion to Tkinter PhotoImage
try:
    from PIL import Image, ImageTk
    PIL_AVAILABLE = True    # flag: True if Pillow is installed
except ImportError:
    PIL_AVAILABLE = False   # app still works, just no cover images

# Requests — HTTP library to download book cover images from Amazon URLs
try:
    import requests
    REQUESTS_AVAILABLE = True
except ImportError:
    REQUESTS_AVAILABLE = False


# =============================================================================
#  SECTION 1 — MODEL LOADER
#  Loads all 4 .pkl files from disk and exposes them as attributes
# =============================================================================

class ModelLoader:
    """
    Reads the 4 pickle files saved by the Jupyter notebook.

    Attributes after calling .load_all()
    popular_df        → pd.DataFrame  : top-50 books
    pt                → pd.DataFrame  : pivot table rows=books, cols=User-IDs
    books             → pd.DataFrame  : full books table
    similarity_scores → np.ndarray    : (706,706) cosine similarity matrix
    """

    def __init__(self, folder='.'):
        # folder: directory where the .pkl files live
        self.folder = folder

    def _load_one(self, filename):
        """Open one pickle file and return its Python object."""
        path = os.path.join(self.folder, filename)   # build full file path

        if not os.path.exists(path):
            raise FileNotFoundError(
                f"Cannot find '{filename}' in:\n{self.folder}\n\n"
                f"Please run the Jupyter notebook completely first.\n"
                f"It will create '{filename}' in the same folder as your CSVs."
            )

        with open(path, 'rb') as f:
            return pickle.load(f)   # 'rb' = read binary mode

    def load_all(self):
        """Load all 4 files and store as instance attributes. Returns self."""
        self.popular_df        = self._load_one('popular.pkl')
        self.pt                = self._load_one('pt.pkl')
        self.books             = self._load_one('books.pkl')
        self.similarity_scores = self._load_one('similarity_scores.pkl')
        return self


# =============================================================================
#  SECTION 2 — RECOMMENDATION ENGINE
#  Wraps the recommend() logic from the Jupyter notebook as a clean class
# =============================================================================

class RecommendationEngine:
    """
    Given a book title, returns N similar books using cosine similarity.
    Same logic as the notebook's recommend() function, wrapped as a class.
    """

    def __init__(self, pt, books_df, similarity_scores):
        self.pt                = pt
        self.books_df          = books_df
        self.similarity_scores = similarity_scores

    def recommend(self, book_name, top_n=4):
        """
        Return top_n books most similar to book_name.

        Returns list of dicts with keys: title, author, image
        """
        # Find the integer position of book_name in the pivot table's row index
        # np.where returns a tuple; [0][0] extracts the first matching index
        index = np.where(self.pt.index == book_name)[0][0]

        # Sort all books by similarity descending, skip index 0 (the book itself)
        similar_items = sorted(
            list(enumerate(self.similarity_scores[index])),
            key=lambda x: x[1],   # sort by similarity score
            reverse=True
        )[1 : top_n + 1]           # take next top_n after skipping itself

        results = []
        for item_idx, _score in similar_items:
            title   = self.pt.index[item_idx]
            matched = self.books_df[self.books_df['Book-Title'] == title]
            matched = matched.drop_duplicates('Book-Title')

            if matched.empty:
                continue

            results.append({
                'title'  : matched['Book-Title'].values[0],
                'author' : matched['Book-Author'].values[0],
                'image'  : matched['Image-URL-M'].values[0],
            })

        return results

    def all_titles(self):
        """Return a sorted list of every book title in the pivot table."""
        return sorted(list(self.pt.index))


# =============================================================================
#  SECTION 3 — IMAGE CACHE
#  Downloads book cover images in background threads and caches the results
# =============================================================================

class ImageCache:
    """
    Downloads Amazon book cover URLs asynchronously and caches PhotoImages.
    Uses daemon threads so downloads never block the UI.
    """

    COVER_W = 120   # thumbnail width  (pixels)
    COVER_H = 165   # thumbnail height (pixels)

    def __init__(self):
        self._cache = {}         # maps URL (str) → PhotoImage
        self._placeholder = None # grey placeholder shown while loading

    def placeholder(self):
        """Return (or create) a grey placeholder PhotoImage."""
        if self._placeholder is None and PIL_AVAILABLE:
            img = Image.new('RGB', (self.COVER_W, self.COVER_H), color='#1E2436')
            self._placeholder = ImageTk.PhotoImage(img)
        return self._placeholder

    def get(self, url, on_done):
        """
        Return cached image immediately, or start a background download.
        on_done: callable(photo) called when the image is ready.
        """
        if not PIL_AVAILABLE or not REQUESTS_AVAILABLE or not url:
            return

        # Already cached — call on_done immediately
        if url in self._cache:
            on_done(self._cache[url])
            return

        def _worker():
            """Background thread: download → resize → cache → callback."""
            try:
                resp  = requests.get(url, timeout=6)
                resp.raise_for_status()

                img   = Image.open(BytesIO(resp.content))
                img   = img.resize((self.COVER_W, self.COVER_H), Image.LANCZOS)
                photo = ImageTk.PhotoImage(img)

                self._cache[url] = photo
                on_done(photo)            # update the Label widget in the UI

            except Exception:
                pass   # silently ignore network / decode errors

        # daemon=True: thread auto-dies when the main window closes
        threading.Thread(target=_worker, daemon=True).start()


# =============================================================================
#  SECTION 4 — BOOK CARD WIDGET
#  One self-contained widget showing a single book
# =============================================================================

class BookCard(tk.Frame):
    """
    A compact card widget showing:
      cover image
      Book Title
      Author Name
      star rating  (only in Popular tab)
    """

    CARD_BG    = '#141824'
    TITLE_FG   = '#FFFFFF'
    AUTHOR_FG  = '#8B95A8'
    RATING_FG  = '#25D366'
    BORDER_COL = '#2A3048'

    def __init__(self, parent, book_data, img_cache, show_rating=False):
        """
        parent      → parent tk widget
        book_data   → dict: title, author, image, [num_ratings, avg_rating]
        img_cache   → shared ImageCache instance
        show_rating → if True, show star rating line
        """
        super().__init__(
            parent,
            bg=self.CARD_BG,
            padx=8, pady=10,
            highlightthickness=1,
            highlightbackground=self.BORDER_COL
        )

        self.book_data   = book_data
        self.img_cache   = img_cache
        self.show_rating = show_rating
        self._photo_ref  = None   # keep reference or GC will delete the image!

        self._build_widgets()

    def _build_widgets(self):
        """Create all child widgets inside this card."""

        # Cover image label — starts with placeholder, updated when download completes
        self.img_label = tk.Label(
            self,
            image=self.img_cache.placeholder(),
            bg=self.CARD_BG
        )
        self.img_label.pack()

        # Title label — wraplength auto-wraps long titles
        tk.Label(
            self,
            text=str(self.book_data.get('title', '')),
            font=('Segoe UI', 8, 'bold'),
            bg=self.CARD_BG,
            fg=self.TITLE_FG,
            wraplength=115,
            justify='center'
        ).pack(pady=(5, 1))

        # Author label — truncate very long names
        tk.Label(
            self,
            text=str(self.book_data.get('author', ''))[:24],
            font=('Segoe UI', 7),
            bg=self.CARD_BG,
            fg=self.AUTHOR_FG
        ).pack()

        # Rating line — only shown in the Popular tab
        if self.show_rating:
            nr  = self.book_data.get('num_ratings', 0)
            avg = self.book_data.get('avg_rating',  0.0)
            tk.Label(
                self,
                text=f'⭐ {float(avg):.1f}  ({int(nr):,} ratings)',
                font=('Segoe UI', 7),
                bg=self.CARD_BG,
                fg=self.RATING_FG
            ).pack(pady=(3, 0))

        # Start background image download
        url = str(self.book_data.get('image', ''))
        if url.startswith('http'):
            self.img_cache.get(url, self._set_image)

    def _set_image(self, photo):
        """Called by ImageCache when the cover download is complete."""
        self._photo_ref = photo               # keep reference to prevent GC
        self.img_label.config(image=photo)    # update label in the UI


# =============================================================================
#  SECTION 5 — SCROLLABLE BOOK GRID
# =============================================================================

class BookGrid(tk.Frame):
    """
    A vertically scrollable canvas that arranges BookCard widgets in a grid.
    """

    GRID_BG = '#0A0E1A'

    def __init__(self, parent, img_cache, cols=5):
        super().__init__(parent, bg=self.GRID_BG)
        self.img_cache = img_cache
        self.cols      = cols
        self._build()

    def _build(self):
        """Create Canvas + Scrollbar + inner Frame."""
        self.canvas = tk.Canvas(self, bg=self.GRID_BG,
                                highlightthickness=0, bd=0)
        self.canvas.pack(side='left', fill='both', expand=True)

        vbar = ttk.Scrollbar(self, orient='vertical', command=self.canvas.yview)
        vbar.pack(side='right', fill='y')
        self.canvas.configure(yscrollcommand=vbar.set)

        self.inner = tk.Frame(self.canvas, bg=self.GRID_BG)
        self._win  = self.canvas.create_window((0, 0), window=self.inner, anchor='nw')

        # When inner frame resizes: update scroll region
        self.inner.bind('<Configure>',  lambda _e: self.canvas.configure(
            scrollregion=self.canvas.bbox('all')))
        # When canvas resizes: stretch inner frame to match
        self.canvas.bind('<Configure>', lambda  e: self.canvas.itemconfig(
            self._win, width=e.width))
        # Mouse-wheel scrolling
        self.canvas.bind_all('<MouseWheel>',
            lambda e: self.canvas.yview_scroll(int(-1*(e.delta/120)), 'units'))

    def populate(self, book_list, show_rating=False):
        """Clear grid and fill with BookCards from book_list."""
        for w in self.inner.winfo_children():
            w.destroy()   # remove all existing cards

        for idx, book in enumerate(book_list):
            row = idx // self.cols    # which row
            col = idx %  self.cols    # which column

            BookCard(
                parent      = self.inner,
                book_data   = book,
                img_cache   = self.img_cache,
                show_rating = show_rating
            ).grid(row=row, column=col, padx=8, pady=8, sticky='n')

        self.canvas.yview_moveto(0)   # scroll to top after populating


# =============================================================================
#  SECTION 6 — MAIN APPLICATION WINDOW
# =============================================================================

class BookRecommenderApp:
    """
    Root Tkinter window with two tabs: Popular Books and Recommend Books.
    """

    # Colour palette
    C_BG      = '#0A0E1A'
    C_PANEL   = '#141824'
    C_INPUT   = '#1E2436'
    C_ACCENT  = '#25D366'
    C_ACCENT2 = '#128C7E'
    C_WHITE   = '#FFFFFF'
    C_GREY    = '#8B95A8'
    C_LIGHT   = '#DCE4F0'
    C_BORDER  = '#2A3048'

    def __init__(self, root, model):
        """
        root  → tk.Tk() main window
        model → ModelLoader instance (already loaded)
        """
        self.root  = root
        self.model = model

        # Build recommendation engine
        self.engine = RecommendationEngine(
            pt                = model.pt,
            books_df          = model.books,
            similarity_scores = model.similarity_scores
        )

        self.all_titles = self.engine.all_titles()  # sorted list of all book titles
        self.img_cache  = ImageCache()              # shared image cache

        self._setup_window()
        self._build_header()
        self._build_notebook()

    # ── Window configuration ──────────────────────────────────────────────────
    def _setup_window(self):
        """Set title, size (90% screen), centre position, dark background."""
        self.root.title('📚  Book Recommender System')

        sw = self.root.winfo_screenwidth()
        sh = self.root.winfo_screenheight()
        w, h = int(sw * 0.90), int(sh * 0.87)
        x, y = (sw - w) // 2, (sh - h) // 2

        self.root.geometry(f'{w}x{h}+{x}+{y}')
        self.root.configure(bg=self.C_BG)
        self.root.resizable(True, True)
        self.root.columnconfigure(0, weight=1)
        self.root.rowconfigure(1, weight=1)   # notebook row expands on resize

    # ── Header bar ────────────────────────────────────────────────────────────
    def _build_header(self):
        """Top bar with green icon, title, subtitle, and stats badge."""
        hdr = tk.Frame(self.root, bg=self.C_PANEL)
        hdr.grid(row=0, column=0, sticky='ew')
        hdr.columnconfigure(1, weight=1)

        # Green icon box
        icon_box = tk.Frame(hdr, bg=self.C_ACCENT, width=54, height=54)
        icon_box.grid(row=0, column=0, padx=(20, 12), pady=14)
        icon_box.grid_propagate(False)
        tk.Label(icon_box, text='📚', font=('Segoe UI Emoji', 22),
                 bg=self.C_ACCENT, fg=self.C_WHITE).place(relx=.5, rely=.5, anchor='center')

        # Title block
        tb = tk.Frame(hdr, bg=self.C_PANEL)
        tb.grid(row=0, column=1, sticky='w')
        tk.Label(tb, text='Book Recommender System',
                 font=('Segoe UI', 17, 'bold'),
                 bg=self.C_PANEL, fg=self.C_WHITE).pack(anchor='w')
        tk.Label(tb, text='Popularity-Based  ·  Collaborative Filtering  ·  Cosine Similarity',
                 font=('Segoe UI', 9),
                 bg=self.C_PANEL, fg=self.C_GREY).pack(anchor='w')

        # Stats badge
        badge = tk.Frame(hdr, bg=self.C_INPUT, padx=14, pady=8)
        badge.grid(row=0, column=2, padx=(0, 20), pady=14)
        tk.Label(badge,
                 text=f'{len(self.model.popular_df)} Popular Books  ·  '
                      f'{len(self.all_titles)} for CF Recommendations',
                 font=('Segoe UI', 9),
                 bg=self.C_INPUT, fg=self.C_ACCENT).pack()

        # Thin green accent line below header
        tk.Frame(self.root, bg=self.C_ACCENT, height=3).grid(
            row=0, column=0, sticky='sew')

    # ── Notebook (2 tabs) ─────────────────────────────────────────────────────
    def _build_notebook(self):
        """Create styled ttk.Notebook with Popular and Recommend tabs."""
        s = ttk.Style()
        s.theme_use('clam')
        s.configure('App.TNotebook', background=self.C_BG, borderwidth=0)
        s.configure('App.TNotebook.Tab', background=self.C_PANEL, foreground=self.C_GREY,
                    padding=[20, 10], font=('Segoe UI', 11))
        s.map('App.TNotebook.Tab',
              background=[('selected', self.C_INPUT), ('active', self.C_INPUT)],
              foreground=[('selected', self.C_ACCENT), ('active', self.C_WHITE)])

        self.nb = ttk.Notebook(self.root, style='App.TNotebook')
        self.nb.grid(row=1, column=0, sticky='nsew', padx=10, pady=(6, 10))

        # Tab 1
        tab_pop = tk.Frame(self.nb, bg=self.C_BG)
        tab_pop.rowconfigure(1, weight=1)
        tab_pop.columnconfigure(0, weight=1)
        self.nb.add(tab_pop, text='🏆  Top 50 Popular Books')

        # Tab 2
        tab_rec = tk.Frame(self.nb, bg=self.C_BG)
        tab_rec.rowconfigure(2, weight=1)
        tab_rec.columnconfigure(0, weight=1)
        self.nb.add(tab_rec, text='🔍  Recommend Books')

        self._fill_popular_tab(tab_pop)
        self._fill_recommend_tab(tab_rec)

    # ── Tab 1 : Popular Books ─────────────────────────────────────────────────
    def _fill_popular_tab(self, parent):
        """Sub-header + 5-column scrollable grid of popular books."""

        # Sub-header
        sub = tk.Frame(parent, bg=self.C_PANEL, pady=10)
        sub.grid(row=0, column=0, sticky='ew', pady=(0, 6))
        tk.Label(sub, text='🏆  Top 50 Most Popular Books',
                 font=('Segoe UI', 13, 'bold'),
                 bg=self.C_PANEL, fg=self.C_WHITE).pack(side='left', padx=20)
        tk.Label(sub, text='Ranked by number of ratings  ·  minimum 250 ratings required',
                 font=('Segoe UI', 9),
                 bg=self.C_PANEL, fg=self.C_GREY).pack(side='left', padx=10)

        # Grid
        grid = BookGrid(parent, self.img_cache, cols=5)
        grid.grid(row=1, column=0, sticky='nsew', padx=4, pady=4)

        # Convert popular_df rows to list of dicts
        books_list = [
            {
                'title'       : row.get('Book-Title',  'Unknown'),
                'author'      : row.get('Book-Author', 'Unknown'),
                'image'       : row.get('Image-URL-M', ''),
                'num_ratings' : row.get('num_ratings',  0),
                'avg_rating'  : row.get('avg_rating',   0.0),
            }
            for _, row in self.model.popular_df.iterrows()
        ]

        grid.populate(books_list, show_rating=True)

    # ── Tab 2 : Recommend Books ───────────────────────────────────────────────
    def _fill_recommend_tab(self, parent):
        """Search bar + autocomplete dropdown + results grid."""

        # Search bar row
        search_bar = tk.Frame(parent, bg=self.C_PANEL, pady=14)
        search_bar.grid(row=0, column=0, sticky='ew', pady=(0, 4))

        tk.Label(search_bar, text='🔍  Type a book title:',
                 font=('Segoe UI', 11, 'bold'),
                 bg=self.C_PANEL, fg=self.C_WHITE).pack(side='left', padx=20)

        # StringVar — trace calls _on_type every time the user types
        self.search_var = tk.StringVar()
        self.search_var.trace_add('write', self._on_type)

        self.entry = tk.Entry(
            search_bar, textvariable=self.search_var,
            font=('Segoe UI', 11), bg=self.C_INPUT, fg=self.C_WHITE,
            insertbackground=self.C_WHITE, relief='flat', bd=0, width=42
        )
        self.entry.pack(side='left', padx=10, ipady=9)
        self.entry.bind('<Return>', lambda _e: self._do_recommend())   # Enter key

        tk.Button(
            search_bar, text='Get Recommendations  →',
            command=self._do_recommend,
            font=('Segoe UI', 10, 'bold'),
            bg=self.C_ACCENT, fg=self.C_WHITE,
            activebackground=self.C_ACCENT2, activeforeground=self.C_WHITE,
            relief='flat', cursor='hand2', padx=16, pady=9, bd=0
        ).pack(side='left', padx=10)

        # Autocomplete dropdown (hidden; placed dynamically below entry)
        self.dropdown_frame = tk.Frame(parent, bg=self.C_BORDER, bd=1)
        self.dropdown_list  = tk.Listbox(
            self.dropdown_frame,
            font=('Segoe UI', 10), bg=self.C_INPUT, fg=self.C_LIGHT,
            selectbackground=self.C_ACCENT, selectforeground=self.C_BG,
            relief='flat', bd=0, height=7, activestyle='none'
        )
        self.dropdown_list.pack(fill='both', expand=True)
        self.dropdown_list.bind('<Double-Button-1>', self._pick_suggestion)
        self.dropdown_list.bind('<Return>',          self._pick_suggestion)

        # Status label
        self.status_var = tk.StringVar(
            value='Type a book title above and press Enter or click the button.')
        tk.Label(parent, textvariable=self.status_var, font=('Segoe UI', 9),
                 bg=self.C_BG, fg=self.C_GREY
                 ).grid(row=1, column=0, sticky='w', padx=16, pady=(0, 4))

        # Results grid (4 columns)
        self.rec_grid = BookGrid(parent, self.img_cache, cols=4)
        self.rec_grid.grid(row=2, column=0, sticky='nsew', padx=4, pady=4)

    # ── Autocomplete ──────────────────────────────────────────────────────────
    def _on_type(self, *_args):
        """Filter all_titles on every keystroke and show the dropdown."""
        query = self.search_var.get().strip().lower()

        if len(query) < 2:
            self.dropdown_frame.place_forget()
            return

        matches = [t for t in self.all_titles if query in t.lower()][:10]

        if not matches:
            self.dropdown_frame.place_forget()
            return

        self.dropdown_list.delete(0, 'end')
        for t in matches:
            self.dropdown_list.insert('end', t)

        # Position dropdown just below the entry box
        ex = self.entry.winfo_x()
        ey = self.entry.winfo_y() + self.entry.winfo_height() + 26
        self.dropdown_frame.place(x=ex, y=ey, width=self.entry.winfo_width() + 20)
        self.dropdown_frame.lift()

    def _pick_suggestion(self, _event):
        """Fill entry with selected suggestion and run recommendation."""
        sel = self.dropdown_list.curselection()
        if not sel:
            return
        self.search_var.set(self.dropdown_list.get(sel[0]))
        self.dropdown_frame.place_forget()
        self._do_recommend()

    # ── Run recommendation ────────────────────────────────────────────────────
    def _do_recommend(self):
        """Read entry → call engine → populate results grid."""
        self.dropdown_frame.place_forget()
        book_name = self.search_var.get().strip()

        if not book_name:
            messagebox.showinfo('No Input', 'Please type a book title first.')
            return

        if book_name not in self.all_titles:
            hints = [t for t in self.all_titles if book_name.lower() in t.lower()][:4]
            hint_text = ('\n\nDid you mean:\n' + '\n'.join(f'  • {h}' for h in hints)
                         if hints else '')
            messagebox.showerror(
                'Book Not Found',
                f'"{book_name}" is not in the model.\n'
                f'Only books rated by 50+ active users are included.{hint_text}')
            return

        self.status_var.set(f'⏳  Finding books similar to "{book_name}" …')
        self.root.update_idletasks()   # force UI to repaint before heavy work

        try:
            results = self.engine.recommend(book_name, top_n=4)
            if not results:
                self.status_var.set('⚠️  No similar books found.')
                return
            self.rec_grid.populate(results, show_rating=False)
            self.status_var.set(f'✅  Showing {len(results)} books similar to "{book_name}"')
        except Exception as exc:
            messagebox.showerror('Error', str(exc))
            self.status_var.set('❌  Error — see dialog.')


# =============================================================================
#  SECTION 7 — ENTRY POINT
# =============================================================================

def main():
    """
    Entry point:
      1. Locate the folder containing this script (where .pkl files should live)
      2. Load all 4 model pickle files
      3. Create the Tkinter root window
      4. Build and launch the app
    """

    # Folder = same directory as app.py
    folder = os.path.dirname(os.path.abspath(__file__))
    print(f'Looking for model files in: {folder}')

    # Load model — show helpful error if any .pkl is missing
    try:
        model = ModelLoader(folder).load_all()
        print(f'  popular_df        : {len(model.popular_df)} rows')
        print(f'  pt (pivot table)  : {model.pt.shape}')
        print(f'  similarity_scores : {model.similarity_scores.shape}')
        print('Model loaded. Launching window …\n')

    except FileNotFoundError as err:
        tmp = tk.Tk()
        tmp.withdraw()   # hide blank root window
        messagebox.showerror('Missing Model Files', str(err))
        tmp.destroy()
        return

    # Create and run the app
    root = tk.Tk()
    BookRecommenderApp(root, model)
    root.mainloop()   # blocks until user closes the window


if __name__ == '__main__':
    main()
